export { default as Moderation } from "./Moderation"
export { default as AddProduct } from "./AddProduct"
export { default as ModifyProduct} from "./ModifyProduct"
export { default as RemoveModal} from "./RemoveModal"
export { default as UpdateProduct} from "./UpdateProduct"